# Generated by Django 5.1.1 on 2024-09-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('asset_no', models.CharField(max_length=100)),
                ('asset_name', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=150)),
                ('remark', models.CharField(max_length=200)),
            ],
        ),
    ]
